'use strict';
window.addEventListener('DOMContentLoaded',()=>{
  const API='https://sharecapsule-reactions.subhafash-86.workers.dev/api/factcheck';
  const $=id=>document.getElementById(id);
  const sourceUrl=$('sourceUrl'),results=$('results'),report=$('report');
  const compareUrl=$('compareUrl'),compareButton=$('compareButton'),compareResult=$('compareResult');
  const historyButton=$('historyButton'),historyPanel=$('historyPanel'),historyList=$('historyList'),clearHistoryButton=$('clearHistoryButton');
  const shareButton=$('shareReportButton'),copyButton=$('copyReportButton'),sharePanel=$('sharePanel'),shareSummary=$('shareSummary');
  const transparency=$('transparency');
  const HISTORY_KEY='sharecapsule-factcheck-history-v1';
  let lastPrimary=null,lastComparison=null,lastSummary='',lastSavedSignature='';
  const clean=(v,m=5000)=>String(v||'').replace(/\0/g,'').replace(/[\u0001-\u001F\u007F]/g,' ').normalize('NFKC').replace(/\s+/g,' ').trim().slice(0,m);
  const safeUrl=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)&&!u.username&&!u.password?u.toString():''}catch{return''}};
  const text=(value,fallback='Not available')=>clean(value||fallback,500);
  function metricRow(parent,label,value){const row=document.createElement('div');row.className='compareRow';const strong=document.createElement('strong');strong.textContent=label;const body=document.createElement('div');body.textContent=text(value);row.append(strong,body);parent.appendChild(row)}
  function transparencyScore(article){if(!article)return{score:0,signals:[]};const signals=[['Publisher identified',Boolean(article.publisher)],['Author identified',Boolean(article.author)],['Publication date',Boolean(article.published)],['Modified date',Boolean(article.modified)],['Canonical URL',Boolean(article.canonicalUrl)],['Official domain',Boolean(article.official)]];let score=0;signals.forEach(([name,ok])=>{score+=ok?(name==='Official domain'?25:15):0});return{score:Math.min(100,score),signals}}
  function renderTransparency(data){transparency.replaceChildren();if(!data?.article)return;const{score,signals}=transparencyScore(data.article);const card=document.createElement('section');card.className='transparencyCard';const h=document.createElement('h2');h.textContent='Source transparency';const wrap=document.createElement('div');wrap.className='transparencyScore';const ring=document.createElement('div');ring.className='scoreRing';ring.style.setProperty('--score',score);const span=document.createElement('span');span.textContent=score+'%';ring.appendChild(span);const copy=document.createElement('div');const grade=document.createElement('strong');grade.textContent=score>=75?'High transparency':score>=45?'Moderate transparency':'Low transparency';const note=document.createElement('p');note.className='phaseCNotice';note.textContent='This measures visible publishing details, not whether the article is true.';copy.append(grade,note);wrap.append(ring,copy);const grid=document.createElement('div');grid.className='transparencySignals';signals.forEach(([label,ok])=>{const box=document.createElement('div');box.className='transparencySignal';const s=document.createElement('strong');s.textContent=label;const v=document.createElement('div');v.textContent=ok?'Present':'Missing';box.append(s,v);grid.appendChild(box)});card.append(h,wrap,grid);transparency.appendChild(card)}
  async function analyzeUrl(url){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({claim:'Compare article source and publication details',sourceUrl:url})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Article analysis failed.');return data}
  function renderComparison(){compareResult.replaceChildren();const a=lastPrimary?.article,b=lastComparison?.article;if(!a||!b)return;const section=document.createElement('section');section.className='comparePanel';const h=document.createElement('h2');h.textContent='Article comparison';const grid=document.createElement('div');grid.className='compareGrid';const left=document.createElement('div');left.className='compareColumn';const lh=document.createElement('h3');lh.textContent='Submitted article';left.appendChild(lh);const right=document.createElement('div');right.className='compareColumn';const rh=document.createElement('h3');rh.textContent='Possible original';right.appendChild(rh);[['Headline','title'],['Publisher','publisher'],['Author','author'],['Published','published'],['Modified','modified'],['Host','host'],['Canonical URL','canonicalUrl']].forEach(([label,key])=>{metricRow(left,label,a[key]);metricRow(right,label,b[key])});grid.append(left,right);const diffs=[];if(clean(a.title).toLowerCase()!==clean(b.title).toLowerCase())diffs.push('The headlines differ.');if(clean(a.publisher).toLowerCase()!==clean(b.publisher).toLowerCase())diffs.push('The publisher names differ.');if(a.published&&b.published&&String(a.published)!==String(b.published))diffs.push('The publication dates differ.');if(a.canonicalUrl&&b.canonicalUrl&&a.canonicalUrl!==b.canonicalUrl)diffs.push('The canonical URLs point to different pages.');if(a.official!==b.official)diffs.push('Only one source has an official-domain signal.');const ul=document.createElement('ul');ul.className='differenceList';(diffs.length?diffs:['No major metadata difference was detected. This does not prove the article text is identical.']).forEach(x=>{const li=document.createElement('li');li.textContent=x;ul.appendChild(li)});section.append(h,grid,ul);compareResult.appendChild(section)}
  compareButton?.addEventListener('click',async()=>{const primary=safeUrl(sourceUrl.value),secondary=safeUrl(compareUrl.value);if(!primary||!secondary){compareResult.textContent='Enter two valid public article URLs.';return}compareButton.disabled=true;const old=compareButton.textContent;compareButton.textContent='Comparing…';try{[lastPrimary,lastComparison]=await Promise.all([analyzeUrl(primary),analyzeUrl(secondary)]);renderComparison();renderTransparency(lastPrimary)}catch(e){compareResult.textContent=clean(e.message,300)}finally{compareButton.disabled=false;compareButton.textContent=old}});
  function buildSummary(){const assessment=report?.querySelector('.assessment')?.textContent||'Insufficient evidence';const source=lastPrimary?.article?.title||document.querySelector('#articleResult .article dd')?.textContent||'Not available';const reviews=document.querySelectorAll('#matches .match').length;return`ShareCapsule investigation\n\nAssessment: ${clean(assessment,300)}\nSource: ${clean(source,300)}\nPublished fact-check reviews: ${reviews}\nChecked: ${new Date().toLocaleString()}\n\nEvidence strength is not a truth score. Review original sources before forwarding.`}
  function saveHistory(){if(!results.classList.contains('show'))return;const entry={id:Date.now(),claim:clean($('claim')?.value||$('videoClaim')?.value||$('ocrText')?.value,240),summary:buildSummary(),createdAt:new Date().toISOString()};const signature=entry.claim+'|'+entry.summary;if(signature===lastSavedSignature)return;lastSavedSignature=signature;let items=[];try{items=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{}items.unshift(entry);localStorage.setItem(HISTORY_KEY,JSON.stringify(items.slice(0,20)))}
  function renderHistory(){historyList.replaceChildren();let items=[];try{items=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{}if(!items.length){const p=document.createElement('p');p.className='emptyHistory';p.textContent='No saved investigations yet. History stays in this browser.';historyList.appendChild(p);return}items.forEach(item=>{const row=document.createElement('div');row.className='historyItem';const main=document.createElement('div');const strong=document.createElement('strong');strong.textContent=item.claim||'Untitled investigation';const meta=document.createElement('div');meta.className='historyMeta';meta.textContent=new Date(item.createdAt).toLocaleString();main.append(strong,meta);const button=document.createElement('button');button.type='button';button.textContent='View';button.onclick=()=>{shareSummary.textContent=item.summary;sharePanel.hidden=false;sharePanel.scrollIntoView({behavior:'smooth'})};row.append(main,button);historyList.appendChild(row)})}
  new MutationObserver(()=>{if(results.classList.contains('show')){lastSummary=buildSummary();saveHistory();renderHistory();const articleTitle=document.querySelector('#articleResult .article');if(articleTitle&&!lastPrimary){const source=safeUrl(sourceUrl.value);if(source)analyzeUrl(source).then(data=>{lastPrimary=data;renderTransparency(data)}).catch(()=>{})}}}).observe(results,{attributes:true,attributeFilter:['class']});
  historyButton?.addEventListener('click',()=>{historyPanel.hidden=!historyPanel.hidden;if(!historyPanel.hidden)renderHistory()});
  clearHistoryButton?.addEventListener('click',()=>{localStorage.removeItem(HISTORY_KEY);lastSavedSignature='';renderHistory()});
  function openShare(){lastSummary=buildSummary();shareSummary.textContent=lastSummary;sharePanel.hidden=false;sharePanel.scrollIntoView({behavior:'smooth'})}
  shareButton?.addEventListener('click',async()=>{openShare();if(navigator.share){try{await navigator.share({title:'ShareCapsule investigation',text:lastSummary})}catch{}}});
  copyButton?.addEventListener('click',async()=>{openShare();try{await navigator.clipboard.writeText(lastSummary);copyButton.textContent='Copied';setTimeout(()=>copyButton.textContent='Copy report',1500)}catch{}});
  renderHistory();
});