const grid=document.getElementById('grid'),pageTitle=document.getElementById('pageTitle'),pageIntro=document.getElementById('pageIntro'),regionLabel=document.getElementById('regionLabel'),regionCount=document.getElementById('regionCount'),disclaimer=document.getElementById('disclaimer'),toast=document.getElementById('toast');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isUs=/\/business\/us(?:\/|$)/i.test(location.pathname);
const pageUrl=item=>`${location.origin}/business/us/#${encodeURIComponent(item.id)}`;
const formatDate=s=>{const d=new Date(`${s}T12:00:00`);return Number.isNaN(d.getTime())?s:d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})};
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1700)}
function shareText(item){return`${item.title}\n\n${item.description}\n\nWatch or listen on Share Capsule:\n${pageUrl(item)}`}
function player(item){const common=`class="player ${item.kind==='audio'?'audio':''}" controls preload="metadata" data-media="${esc(item.id)}"`;if(item.kind==='video')return`<video ${common} playsinline><source src="${esc(item.mediaUrl)}" type="${esc(item.mimeType||'video/mp4')}">Your browser cannot play this video.</video>`;return`<audio ${common}><source src="${esc(item.mediaUrl)}" type="${esc(item.mimeType||'audio/mp4')}">Your browser cannot play this audio.</audio>`}
function card(item){return`<article class="card" id="${esc(item.id)}"><div class="cover" style="background:${esc(item.coverBackground)}"><div class="kind">${esc(item.region)} · ${esc(item.kind)}</div><div class="coverText">${(item.coverLines||[item.title]).map(esc).join('<br>')}</div></div><div class="meta"><h2>${esc(item.title)}</h2><p class="byline">${esc(item.creator)} · ${esc(formatDate(item.publishedAt))}</p><p class="description">${esc(item.description)}</p>${player(item)}<div class="actions"><button class="share" data-share="${esc(item.id)}">Share</button><button data-copy="${esc(item.id)}">Copy link</button><a href="${esc(item.mediaUrl)}" target="_blank" rel="noopener">Open media ↗</a></div><div class="status" data-status="${esc(item.id)}">Hosted in the Cloudflare R2 businessvideos bucket.</div></div></article>`}
function bind(items){grid.querySelectorAll('[data-media]').forEach(media=>media.addEventListener('error',()=>{const status=grid.querySelector(`[data-status="${CSS.escape(media.dataset.media)}"]`);if(status){status.classList.add('error');status.textContent='Media could not be loaded. Confirm that the R2 object is publicly readable and permits browser playback.'}}));grid.querySelectorAll('[data-share]').forEach(button=>button.onclick=async()=>{const item=items.find(x=>x.id===button.dataset.share);if(!item)return;const payload={title:item.title,text:item.description,url:pageUrl(item)};if(navigator.share){try{await navigator.share(payload);return}catch(e){if(e.name==='AbortError')return}}try{await navigator.clipboard.writeText(shareText(item));showToast('Share text copied')}catch{location.href='https://wa.me/?text='+encodeURIComponent(shareText(item))}});grid.querySelectorAll('[data-copy]').forEach(button=>button.onclick=async()=>{const item=items.find(x=>x.id===button.dataset.copy);if(!item)return;try{await navigator.clipboard.writeText(pageUrl(item));showToast('Link copied')}catch{showToast('Copy unavailable')}})}
async function load(){try{const response=await fetch(`/business/data.json?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json(),all=data.media||[],items=isUs?all.filter(x=>String(x.region).toUpperCase()==='US'):all;document.title=isUs?'U.S. Business — Share Capsule':'Business — Share Capsule';pageTitle.textContent=isUs?'U.S. Business':'Business';pageIntro.textContent=isUs?'Audio and video on U.S. markets, companies and economic developments.':data.site?.tagline||'Business audio and video worth passing on.';regionLabel.textContent=isUs?'United States':'All business regions';regionCount.textContent=`${items.length} item${items.length===1?'':'s'}`;disclaimer.textContent=data.site?.disclaimer||'';grid.innerHTML=items.length?items.map(card).join(''):'<div class="empty">No business media is available.</div>';bind(items);if(location.hash){const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target)setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:'start'}),120)}}catch(error){grid.innerHTML=`<div class="empty"><h2>Business media unavailable</h2><p>${esc(error.message)}</p></div>`}}
load();
