(()=>{
  const API='https://sharecapsule-reactions.subhafash-86.workers.dev';
  let deferredPrompt=null;
  const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
  const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);
  const base64ToUint8=value=>{const padding='='.repeat((4-value.length%4)%4);const raw=atob((value+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));};
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
  const install=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;render();return;}if(ios)alert('On iPhone or iPad: tap Share, then choose “Add to Home Screen”.');else alert('Open your browser menu and choose “Install app” or “Add to Home screen”.');};
  const subscribe=async button=>{if(!('serviceWorker'in navigator)||!('PushManager'in window)){button.textContent='Notifications unsupported';button.disabled=true;return;}if(Notification.permission==='denied'){alert('Notifications are blocked in browser settings for this site.');return;}button.disabled=true;button.textContent='Enabling…';try{const registration=await navigator.serviceWorker.ready;const keyResponse=await fetch(`${API}/api/push/public-key`,{cache:'no-store'});if(!keyResponse.ok)throw new Error('Notification service is not configured yet.');const {publicKey}=await keyResponse.json();const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not granted.');let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToUint8(publicKey)});const response=await fetch(`${API}/api/push/subscribe`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription,source:location.pathname,userAgent:navigator.userAgent})});if(!response.ok)throw new Error('Could not save the notification subscription.');button.textContent='Notifications enabled';button.dataset.enabled='true';}catch(error){button.disabled=false;button.textContent='Notify me';alert(error.message);}};
  const render=()=>{if(document.getElementById('sharecapsulePwaBar'))return;const anchor=document.getElementById('sharecapsuleEndpoints')||document.getElementById('sharecapsuleBreadcrumbs');if(!anchor)return;const bar=document.createElement('section');bar.id='sharecapsulePwaBar';bar.className='sharecapsulePwaBar';bar.innerHTML=`<div><strong>${standalone?'Share Capsule app':'Get the Share Capsule app'}</strong><span>${standalone?'Installed on this device':'Install for faster access and offline pages'}</span></div><div class="sharecapsulePwaActions">${standalone?'':`<button type="button" id="sharecapsuleInstall">Install</button>`}<button type="button" id="sharecapsuleNotify">Notify me</button></div>`;anchor.insertAdjacentElement('afterend',bar);document.getElementById('sharecapsuleInstall')?.addEventListener('click',install);document.getElementById('sharecapsuleNotify')?.addEventListener('click',event=>subscribe(event.currentTarget));};
  window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;render();});
  ready(async()=>{if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('/sw.js',{scope:'/'});}catch(error){console.warn('PWA registration failed',error);}}render();});
})();