const CACHE='sharecapsule-v3';
const APP_SHELL=['/','/offline.html','/site-shell.js','/pwa.js','/manifest.webmanifest','/assets/sharecapsule-logo.svg?v=3','/name/history/tn/','/name/history/tn/places.js','/name/history/tn/tamil.js','/name/history/tn/vote-api.js','/name/history/tn/extra-places.js'];
const isApi=url=>url.pathname.startsWith('/api/');
const isStatic=url=>/\.(?:js|css|svg|png|jpe?g|webp|gif|ico|woff2?)$/i.test(url.pathname);
const isDocument=request=>request.mode==='navigate'||request.destination==='document';
async function cacheFirst(request){const hit=await caches.match(request);if(hit)return hit;const response=await fetch(request);if(response.ok&&response.type==='basic'){const cache=await caches.open(CACHE);cache.put(request,response.clone());}return response}
async function staleWhileRevalidate(request){const cache=await caches.open(CACHE);const hit=await cache.match(request);const update=fetch(request).then(response=>{if(response.ok&&response.type==='basic')cache.put(request,response.clone());return response}).catch(()=>null);return hit||await update||new Response('',{status:503,statusText:'Offline'})}
async function networkFirst(request){const cache=await caches.open(CACHE);try{const response=await fetch(request);if(response.ok&&response.type==='basic')cache.put(request,response.clone());return response}catch{const hit=await cache.match(request);if(hit)return hit;if(isDocument(request))return caches.match('/offline.html');return new Response('',{status:503,statusText:'Offline'})}}
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(APP_SHELL)));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))));self.clients.claim();});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;let url;try{url=new URL(event.request.url)}catch{return}if(url.origin!==location.origin)return;if(isApi(url)){event.respondWith(fetch(event.request));return}if(isStatic(url)){event.respondWith(cacheFirst(event.request));return}if(isDocument(event.request)){event.respondWith(networkFirst(event.request));return}event.respondWith(staleWhileRevalidate(event.request));});
self.addEventListener('push',event=>{let data={};try{data=event.data?event.data.json():{};}catch{data={body:event.data?.text()||'A new Share Capsule post is available.'};}const title=data.title||'New on Share Capsule';const options={body:data.body||'Open Share Capsule to see the latest post.',icon:'/assets/sharecapsule-logo.svg?v=3',badge:'/assets/sharecapsule-logo.svg?v=3',data:{url:data.url||'/'},tag:data.tag||'sharecapsule-new-post',renotify:true};event.waitUntil(self.registration.showNotification(title,options));});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=new URL(event.notification.data?.url||'/',self.location.origin).href;event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const client of list){if(client.url===target&&'focus'in client)return client.focus();}return clients.openWindow(target);}));});